### ISSUE TITLE
Production site does not use HTTP2

### ISSUE THREAD

**Issue by angeloanan** [PretendoNetwork/mario_kart_8_website#2]
The current production deployment site seems to load very slow.

After looking at the browser's network graph it seems that the web server is serving data using HTTP/1.1
This causes slow loading times between JS chunks and didn't allow for multiplexed (parallel) data transfers

I'm assuming production is serving over nginx (that's what the request headers tells anyway)
A quick fix for this is to simply add `http2` to every `listen` directives on the nginx
Read more: https://www.digitalocean.com/community/tutorials/how-to-set-up-nginx-with-http-2-support-on-ubuntu-20-04

**Comment by EpicUsername12** [comment]
Yeah, indeed it is serving over nginx!

I toggled ``http2`` on the official website
